name: module-dask
dependencies:
 - python=3
 - jupyter
 - numpy
 - pandas
 - matplotlib
 - numba
 - dask
 - distributed
 - memory_profiler
 - h5py
 - snakeviz=0.4.0
 - accelerate
 - scipy
 - pytables
 - s3fs
 - graphviz
 - pillow
 - pip:
   - graphviz
   - cachey
